name: Telegram Quiz Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libreoffice
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run the script
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        COLLECTION_NAME: ${{ secrets.COLLECTION_NAME }}
        MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
        TEMPLATE_URL: ${{ secrets.TEMPLATE_URL }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      run: |
        python main.py
